# Generated by Django 4.2.7 on 2025-06-18 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FraudAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('total_claims', models.IntegerField(default=0)),
                ('low_risk_count', models.IntegerField(default=0)),
                ('medium_risk_count', models.IntegerField(default=0)),
                ('high_risk_count', models.IntegerField(default=0)),
                ('critical_risk_count', models.IntegerField(default=0)),
                ('output_csv_path', models.CharField(blank=True, max_length=500)),
                ('high_risk_csv_path', models.CharField(blank=True, max_length=500)),
                ('visualizations', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(max_length=100)),
                ('claimant_name', models.CharField(max_length=200)),
                ('date_of_loss', models.DateField(blank=True, null=True)),
                ('injury_type', models.CharField(blank=True, max_length=200)),
                ('body_part', models.CharField(blank=True, max_length=200)),
                ('fraud_score', models.FloatField(default=0)),
                ('risk_level', models.CharField(choices=[('Low', 'Low Risk'), ('Medium', 'Medium Risk'), ('High', 'High Risk'), ('Critical', 'Critical Risk')], default='Low', max_length=20)),
                ('red_flags', models.JSONField(default=list)),
                ('days_to_report', models.IntegerField(blank=True, null=True)),
                ('claim_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='fraud_detector.fraudanalysis')),
            ],
            options={
                'ordering': ['-fraud_score'],
            },
        ),
    ]
